### ISSUE TITLE
Uncaught Error: Call to undefined function Andig\imagecreatefromstring()

### ISSUE THREAD

**Issue by der-domi** [andig/carddav2fb#213]
I'm using the latest/master version. Currently I'm facing following issue. Is there went something wrong in one of the commits?

Thanks, Dominik

```
Downloading recent FRITZ!Box phonebook
No special attributes are saved!
Downloading vCard(s) from account XXX
    0 [>---------------------------]
    1 [->--------------------------]
Downloaded 130 vCard(s)
Downloading vCard(s) from account XXX
    0 [>---------------------------]
    1 [->--------------------------]
Downloaded 16 vCard(s)
Downloaded 146 vCard(s) in total
Dissolving groups (e.g. iCloud)
Dissolved 0 group(s)
Filtering 146 vCard(s)
Filtered 79 vCard(s)
Detaching and uploading image(s)
  0/67 [>---------------------------]   0%
  7/67 [==>-------------------------]  10%PHP Fatal error:  Uncaught Error: Call to undefined function Andig\imagecreatefromstring() in /srv/src/functions.php:132
Stack trace:
#0 /srv/src/functions.php(187): Andig\convertPNGtoJPG('\x89PNG\r\n\x1A\n\x00\x00\x00\rIHD...')
#1 /srv/src/functions.php(255): Andig\getJPEGimage(Object(Sabre\VObject\Component\VCard))
#2 /srv/src/RunCommand.php(71): Andig\uploadImages(Array, Array, Array, Object(Closure))
#3 /srv/vendor/symfony/console/Command/Command.php(258): Andig\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /srv/vendor/symfony/console/Application.php(911): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /srv/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Andig\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) in /srv/src/functions.php on line 132
```

**Comment by der-domi** [comment]
Sorry. I've created my own image. But the Dockerfile was not up-to-date.
