### ISSUE TITLE
Argument 1 passed to Andig\filter() must be of the type array

### ISSUE THREAD

**Issue by Stefan300381** [andig/carddav2fb#45]
Woran koennte es hier scheitern?

```
php carddav2fb.php convert -vvv out

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Andig\filter() must be of the type array, null given, called in /opt/carddav2fb/src/ConvertCommand.php on line 37 and defined in /opt/carddav2fb/src/functions.php:132
Stack trace:
#0 /opt/carddav2fb/src/ConvertCommand.php(37): Andig\filter(NULL, Array)
#1 /opt/carddav2fb/vendor/symfony/console/Command/Command.php(252): Andig\ConvertCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /opt/carddav2fb/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /opt/carddav2fb/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Andig\ConvertCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /opt/carddav2fb/vendor/symfony/console/Application. in /opt/carddav2fb/src/functions.php on line 132
```

**Comment by andig** [comment]
Wie sieht Deine Config (ohne Passwörter) aus?

**Comment by andig** [comment]
Looks like in https://github.com/andig/carddav2fb/blob/master/src/ConvertCommand.php#L37 the `cards` is not an array. What's in your `out` file- is it empty or invalid json?

**Comment by andig** [comment]
I've added code to guard against that. Empty is not valid json- it should at least be an empty json array. If empty files get generated please open a new issue so we can figure out why that happens.
