### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Andig\export()

### ISSUE THREAD

**Issue by jandechent** [andig/carddav2fb#61]
Attached:

```
Downloaded 1996 vCard(s)
Parsing vcards
Converted 1996 vcard(s)
PHP Notice:  Undefined index: phonebook in /home/user/Documents/fritz.box/carddav2fb/src/RunCommand.php on line 70
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Andig\export() must be of the type string, null given, called in /home/user/Documents/fritz.box/carddav2fb/src/RunCommand.php on line 72 and defined in /home/user/Documents/fritz.box/carddav2fb/src/functions.php:251
Stack trace:
#0 /home/user/Documents/fritz.box/carddav2fb/src/RunCommand.php(72): Andig\export(NULL, Array, Array)
#1 /home/user/Documents/fritz.box/carddav2fb/vendor/symfony/console/Command/Command.php(251): Andig\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/user/Documents/fritz.box/carddav2fb/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/user/Documents/fritz.box/carddav2fb/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Andig\RunCommand), Object(Symfon in /home/user/Documents/fritz.box/carddav2fb/src/functions.php on line 251
```

**Comment by andig** [comment]
Seems this is no longer an issue? If it reoccurs please feel free to reopen this issue.
